# ===============
# Alan Fixed Slab
# ===============

[buildPlans.alan-fixed-slab]
family = "Alan Fixed Slab"
spacing = "fixed"
serifs = "slab"
no-cv-ss = true

[buildPlans.alan-fixed-slab.variants.design]
percent = "rings-continuous-slash"

[buildPlans.alan-fixed-slab.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.alan-fixed-slab.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.alan-fixed-slab.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.alan-fixed-slab.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.alan-fixed-slab.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.alan-fixed-slab.metric-override]
xHeight = 492
leading = 1250

[collectPlans.alan-fixed-slab]
from = ["alan-fixed-slab"]
